<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Xceed.Wpf.Toolkit">
      <HintPath>..\..\..\..\Downloads\Extended.WPF.Toolkit.Binaries.NET\Extended.WPF.Toolkit.Binaries.NET\Xceed.Wpf.Toolkit.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
